---
title: "Statistical Thinking for the 21st Century"
author: "Copyright 2019 Russell A. Poldrack"
date: "Draft: `r Sys.Date()`"
knit: "bookdown::render_book"
bibliography: ["psych10-book.bib"]
biblio-style: "apalike"
documentclass: book
link-citations: yes
github-repo: poldrack/psych10-book
description: "A book about statistics."
always_allow_html: yes
fontsize: 12pt
monofont: "Source Code Pro"
monofontoptions: "Scale=0.7"
output:
  bookdown::pdf_book:
    keep_tex: yes
  bookdown::gitbook:
    lib_dir: "book_assets"
    config:
      edit: https://github.com/poldrack/psych10-book/edit/master/%s
    includes:
      in_header:
        - google_analytics.html
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=6, fig.height=6, #echo=FALSE, 
                      warning=FALSE, message=FALSE)
```

# Preface {-}

The goal of this book is to the tell the story of statistics as it is used today by researchers around the world.  It's a different story than the one told in most introductory statistics books, which focus on teaching how to use a set of tools to acheive very specific goals.  This book focuses on understanding the basic ideas of *statistical thinking* --- a systematic way of thinking about how we describe the world and make decisions and predictions, all in the context of the inherent uncertainty that exists in the real world. It also brings to bear current methods that have only become feasible in light of the amazing increases in computational power that have happened in the last few decades. Analyses that would have taken years in the 1950's can now be completed in a few seconds on a standard laptop computer, and this power unleashes the ability to use computer simulation to ask questions in new and powerful ways.  

The book is also written in the wake of the reproducibility crisis that has engulfed many areas of science since 2010.  One of the important roots of this crisis is found in the way that statistical hypothesis testing has been used (and abused) by researchers (as I detail in the final chapters of the book), and this ties directly back to statistical education.  Thus, a goal of the book is to highlight the ways in which current statistical methods may be problematic, and to suggest alternatives.

## Why does this book exist?

In 2018 I began teaching an undergraduate statistics course at Stanford (Psych 10/Stats 60).  I had never taught statistics before, and this was a chance to shake things up.  I have been increasingly unhappy with undergraduate statistics education in psychology, and I wanted to bring a number of new ideas and approaches to the class.  In particular, I wanted to bring to bear the approaches that are increasingly used in real statistical practice in the 21st century.  As Brad Efron and Trevor Hastie laid out so nicely in their book "Computer Age Statistical Inference: Algorithms, Evidence, and Data Science", these methods take advantage of today's increased computing power to solve statistical problems in ways that go far beyond the more standard methods that are usually taught in the undergraduate statistics course for psychology students.

The first year that I taught the class, I used Andy Field's amazing graphic novel statistics book, "An Adventure in Statistics", as the textbook.  There are many things that I really like about this book -- in particular, I like the way that it frames statistical practice around the building of models, and treats null hypothesis testing with sufficient caution (though insufficient disdain, in my opinion). Unfortunately, most of my students hated the book, primarily because it involved wading through a lot of story to get to the statistical knowledge.  I also found it wanting because there are a number of topics (particular those from the field of artificial intelligence known as *machine learning*) that I wanted to include but were not discussed in his book.  I ultimately came to feel that the students would be best served by a book that follows very closely to my lectures, so I started writing down my lectures into a set of computational notebooks that would ultimately become this book.  The outline of this book follows roughly that of Field's book, since the lectures were originally based in large part on the flow of that book, but the content is substantially different (and also much less fun and clever).


## Why R?

In my course, students learn to analyze data hands-on using the R language.  The question "Why R?" could be interpreted to mean "Why R instead of a graphical software package like (insert name here)?".  After all, most of the students who enroll in my class have never programmed before, so teaching them to program is going to take away from instruction in statistical concepts.  My answer is that I think that the best way to learn statistical tools is to work directly with data, and that working with graphical packages insulates one from the data and methods in way that impedes true understanding.  In addition, for many of the students in my class this may be the only course in which they are exposed to programming; given that programming is an essential ability in a growing number of academic fields, I think that providing these students with basic programming literacy is critical to their future success, and will hopefully inspire at least a few of them to learn more.

The question could also be interpreted to mean "Why R instead of (insert language here)?".  On this question I am much more conflicted, because I deeply dislike R as a programming language (I greatly prefer to use Python for my own work).  Why then do I use R? The first reason is that R has become the "lingua franca" for statistical analysis.  There are a number of tools that I use in this book (such as the linear modeling tools in the `lme4` package and the Bayes factor tools in the `BayesFactor` package) that are simply not available in other languages. 

The second reason is that the free Rstudio software makes using R relatively easy for new users.  In particular, I like the RMarkdown Notebook feature that allows the mixing of narrative and executable code with integrated output.  It's similar in spirit to the Jupyter notebooks that many of us use for Python programming, but I find it easier to deal with because you edit it as a plain text file, rather than through an HTML interface.  In my class, I give students a skeleton RMarkdown file for problem sets, and they submit the file with their solution added, which I then score using a set of automated grading scripts. 

The third reason is practical -- nearly all of the potential teaching assistants (mostly graduate students in our department) have experience with R, since our graduate statistics course uses R.  In fact, most of them have much greater skill with R than I do!  On the other hand, relatively few of them have expertise in Python.  Thus, if I want an army of knowledgeable teaching assistants who can help me when I start flailing during my in-class live coding demos, it makes sense to use R. 

## The golden age of data

Throughout this book I have tried when possible to use examples from real data.  This is now very easy because we are swimming in open datasets, as governments, scientists, and companies are increasingly making data freely available.  I think that using real datasets is important because it prepares students to work with real data rather than toy datasets, which I think should be one of the major goals of statistical training. It also helps us realize (as we will see at various points throughout the book) that data don't always come to us ready to analyze, and often need *wrangling* to help get them into shape.  Using real data also shows that the idealized statistical distributions often assumed in statistical methods don't always hold in the real world -- for example, as we will see in Chapter \@ref(summarizing-data), distributions of some real-world quantities (like the number of friends on Facebook) can have very long tails that can break many standard assumptions.  

I apologize up front that the datasets are heavily US-centric.  This is primarily because the best dataset for many of the demonstrations is the National Health and Nutrition Examination Surveys (NHANES) dataset that is available as an R package, and because many of the other complex datasets included in R (such as those in the `fivethirtyeight` package) are also based in the US.  If you have suggestions for datasets from other regions, please pass them along to me!

## An open source book

This book is meant to be a living document, which is why its source is available online at [https://github.com/poldrack/psych10-book](https://github.com/poldrack/psych10-book).  If you find any errors in the book or want to make a suggestion for how to improve it, please open an issue on the Github site. Even better, submit a pull request with your suggested change.  

The book is licensed according to the [Creative Commons Attribution-NonCommercial 2.0 Generic (CC BY-NC 2.0) License](https://creativecommons.org/licenses/by-nc/2.0/).  Please see the terms of that license for more details.

## Acknowledgements

I'd first like to thank Susan Holmes, who first inspired me to consider writing my own statistics book.  Lucy King provided detailed comments and edits on the entire book, and helped clean up the code so that it was consistent with the Tidyverse.  Michael Henry Tessler provided very helpful comments on the Bayesian analysis chapter. Particular thanks also go to Yihui Xie, creator of the Bookdown package, for improving the book's use of Bookdown features (including the ability for users to directly generate edits via the Edit button).  

I'd also like to thank others who provided helpful comments and suggestions: Athanassios Protopapas, Wesley Tansey, Jack Van Horn, Thor Aspelund.

Thanks to the following Twitter users for helpful suggestions: \@enoriverbend

Thanks to the following individuals/usernames for submitting edits or issues via Github or email: Mehdi Rahim, Shanaathanan Modchalingam, Alan He, Wenjin Tao,  Martijn Stegeman, Dan Kessler, Philipp Kuhnke, James Kent, Michael Waskom, Alexander Wang, Isis Anderson, Albane Valenzuela, Chuanji Gao, Jassary Rico-Herrera, Isil Bilgin, basicv8vc, jiamingkong, carlosivanr, hktan, ttaweel, epetsen, brettelizabeth, lbersh .
